#
# These are supported funding model platforms
# More info at: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository
#

# Setup with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: [davorpa, davorpatech]

# Replace with a single Patreon username
#patreon: 

# Replace with a single Open Collective username
#open_collective: 

# Replace with a single Ko-fi username
#ko_fi: 

# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#tidelift: 

# Replace with a single Community Bridge project-name e.g., cloud-foundry
#community_bridge: 

# Replace with a single Liberapay username
#liberapay: 

# Replace with a single IssueHunt username
#issuehunt: 

# Replace with a single Otechie username
#otechie: 

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
#custom: 

#
# Note: If a custom URL in an array includes :, you must wrap the URL in quotes.
# For example, "https://www.paypal.me/octocat".
#
